### ISSUE TITLE
More features?

### ISSUE THREAD

**Issue by aarony1993** [ROFLailXGOD/twitch-farmer#11]
Hey there. I know this is just a small private project, but after finally making it work, I'm in love with it. Thank you for your work.

Do you still work on it and do you plan to add more features? I'm thinking of something like adding a possibility to target certain streamers? Maybe by channel name or by language or something.

Or is there a way to do this already, that I'm missing?

**Comment by ROFLailXGOD** [comment]
Hello. Honestly, I don't really see a point in this app anymore, because Twitch stopped giving away emotes. I guess you can still use it for gift subs. Anyway, adding a feature that will allow you to connect to specific streamers (by their channel name) shouldn't be hard to implement. I just need to find some free time for that. Feel free to nag me again if I don't do anything in like 2 weeks :)

**Comment by aarony1993** [comment]
Yes exactly, I only use it for gifted subs, which is also some kind of 'emote farming', even though temporary. Thanks for your swift reply!

**Comment by ROFLailXGOD** [comment]
Added a feature that allows you to specifiy channels you want to connect to. It's in settings/base.py. Example:
```python
CHANNELS = ['zazaza691', 'esl_csgo']
```
More info can be found in README.md. If you have any questions, feel free to ask. If something doesn't work, then feel free to reopen this issue
